### ISSUE TITLE
beginner_source/deep_learning_nlp_tutorial.rst 번역

### ISSUE THREAD

**Issue by KimUJeon** [9bow/PyTorch-tutorials-kr#106]
## 문서 URL
_번역을 하실 / 요청하실 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/saving_loading_models.html)_
- **URL**: https://github.com/9bow/PyTorch-tutorials-kr/blob/master/beginner_source/deep_learning_nlp_tutorial.rst

## (대략적인) 예상 완료 일정
_예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)_<br />
_(반드시 지키셔야 하는 일정이 아닙니다 - 일정이 너무 늦어질 경우 다른 번역자를 위해 남겨주세요.)_
8월 10일 이전

## 관련 이슈
_현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다._ <br />
_(특별한 일이 없다면 수정하지 않으셔도 됩니다.)_
#90 (v1.6)

**Comment by 9bow** [comment]
안녕하세요, 번역을 진행해주시려는 문서는 NLP 튜토리얼 시리즈의 인트로격인 문서입니다.
괜찮으시다면 해당 튜토리얼 시리즈에 해당하는 하위 문서들을 먼저 번역 후, 인트로 문서의 번역을 진행해주시기를 부탁드립니다.
하위 문서들은 남기신 링크 또는 다음 링크에서 확인하실 수 있습니다. https://tutorials.pytorch.kr/beginner/deep_learning_nlp_tutorial

**Comment by KimUJeon** [comment]
이곳에서 번역을 처음하다 보니 잘 몰랐었네요... 죄송합니다!
하위 문서 번역 신청해두겠습니다!

**Comment by 9bow** [comment]
앗, 아닙니다. 이미 [시리즈 중 임베딩 튜토리얼](https://tutorials.pytorch.kr/beginner/nlp/word_embeddings_tutorial.html#sphx-glr-beginner-nlp-word-embeddings-tutorial-py)이 번역이 된 상태라서, 시리즈의 뚜껑(?)격만 달랑 번역이 되면 찾아보시는 분들께 혼란이 있으실 수 있을 것 같아 요청드렸습니다. ^^
이해해주시고 새로운 이슈를 남겨주셔서 감사합니다!

**Comment by 9bow** [comment]
오랜기간 진행이 없으셔서 본 이슈를 닫습니다.
이후 기여가 가능하실 때 다시 이슈를 열어주시기를 부탁드립니다. :)
