### ISSUE TITLE
nlp/deep_learning_tutorial.py 번역합니다

### ISSUE THREAD

**Issue by kwonmha** [9bow/PyTorch-tutorials-kr#145]
## 문서 URL
_번역을 하실 / 요청하실 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/saving_loading_models.html)_
- **URL**: https://github.com/9bow/PyTorch-tutorials-kr/blob/master/beginner_source/nlp/deep_learning_tutorial.py

## (대략적인) 예상 완료 일정
_예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)_<br />
8월 30일

## 관련 이슈
_현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다._ <br />
_(특별한 일이 없다면 수정하지 않으셔도 됩니다.)_
#90 (v1.6)

**Comment by Gangsss** [comment]
컨트리뷰톤 리뷰 진행합니다

**Comment by kwonmha** [comment]
이미 PR(#124)이 올라와 있어서 종료하고 다른 파일 번역 진행하겠습니다.
