### ISSUE TITLE
dist_tuto.rst 변경 내역을 반영하겠습니다.

### ISSUE THREAD

**Issue by k1101jh** [9bow/PyTorch-tutorials-kr#15]
## 문서 URL
#14 의 5번 dist_tuto.rst의 변경 내역을 반영하겠습니다.
- **URL**:[intermediate_source/dist_tuto.rst](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/intermediate_source/dist_tuto.rst)

## (대략적인) 예상 완료 일정
11월 말로 예상하고 있습니다.

**Comment by 9bow** [comment]
@k1101jh 
감사합니다! 현재 0.4 기준으로 번역된 내용이 [번역 사이트](https://tutorials.pytorch.kr/intermediate/dist_tuto.html)에 게재되어 있으니 참고 부탁드립니다.
(0.4 기준의 번역 원문은 [여기](https://github.com/9bow/PyTorch-tutorials-kr/blob/0.4/intermediate_source/dist_tuto.rst)에 있습니다.)

감사합니다. :)

**Comment by 9bow** [comment]
노파심에서 말씀드리면, 혹시 https://github.com/9bow/PyTorch-tutorials-kr/issues/14#issuecomment-557569071 내용 때문에 #14의 5번에 해당하는 문서를 선택하신거라면 다른 문서를 먼저 고르셔도 상관없습니다. ^^

**Comment by 9bow** [comment]
기존 번역을 참고하지 않고 새롭게 번역을 진행하여 추가할 예정입니다.
