### ISSUE TITLE
beginner_source/dist_overview.rst 문서 404 File not found

### ISSUE THREAD

**Issue by codingbowoo** [9bow/PyTorch-tutorials-kr#151]
## 이슈 내용

**병렬 및 분산 학습** 대분류 아래의 **PyTorch Distributed Overview** 항목의 경로가 깨진 것 같습니다. 

1. 메인 페이지(https://tutorials.pytorch.kr/) 에서 접근시 404 File not found가 뜹니다.
2. 일부 링크에서 **Table of Contents**를 눌렀을 때 **PyTorch Distributed Overview** 항목이 노출이 되지 않습니다. 해당하는 링크 2개를 첨부합니다. (더 있을 수도 있습니다.)
- https://tutorials.pytorch.kr/intermediate/model_parallel_tutorial.html
- https://tutorials.pytorch.kr/beginner/aws_distributed_training_tutorial.html 

## 추가 정보
- 원본 튜토리얼 링크
    - https://github.com/9bow/PyTorch-tutorials-kr/blob/master/beginner_source/dist_overview.rst
    - https://pytorch.org/tutorials/beginner/dist_overview.html
- 번역본 튜토리얼 링크
    - https://github.com/9bow/PyTorch-tutorials-kr/blob/master/beginner_source/dist_overview.rst
    - https://tutorials.pytorch.kr/beginner/dist_overview.html

**Comment by 9bow** [comment]
제보 감사합니다!
빌드 서버에 문제가 있어 최근 빌드를 못하고 있는데요, 관련해서 함께 살펴보도록 하겠습니다.

**Comment by 9bow** [comment]
감사합니다. 살펴보니 `.gitignore`에서 경로가 지정되지 않고 추가된 Sphinx 빌드 결과물 디렉토리들이 새로 추가된 파일들을 무시하고 있었던 것으로 보여서 수정하였습니다.
덕분에 무시당하던 다른 파일들도 구제가 되었습니다. 🎉
위 1,2번 이슈 모두 해결된 것을 확인하였는데요, 혹시 몰라 확인하시고 닫아주십사 하고 닫지는 않고 남겨두겠습니다. :)

 감사합니다! 👍

**Comment by codingbowoo** [comment]
확인했습니다! 잘 보입니다 👍
