### ISSUE TITLE
'FLASK를 이용하여 PYTHON에서 PYTORCH를 REST API로 배포하기'에서 설치 코드 문제

### ISSUE THREAD

**Issue by 0xBono** [9bow/PyTorch-tutorials-kr#198]
https://github.com/9bow/PyTorch-tutorials-kr/blob/e48bbbc7088bf6b9da66abb8862b8d0539662bd5/intermediate_source/flask_rest_api_tutorial.py#L50

-가 아니라 ==으로 변경되어야 할 것 같습니다.
`torchvision-0.3.0 ` → `torchvision==0.3.0 `

**Comment by 9bow** [comment]
감사합니다, @0xBono 님.
확인해보니 [원문](https://github.com/pytorch/tutorials/blob/master/intermediate_source/flask_rest_api_tutorial.py#L49)에도 수정이 필요할거 같은데요, 혹시 PR 남겨주실 계획이 있으신지요? :)
(없으시다면 알려주시면 제가 변경토록 하겠습니다.)

**Comment by 0xBono** [comment]
@9bow 바로 수정하겠습니다. 빠른 확인 감사합니다 :)

**Comment by 0xBono** [comment]
> @9bow 바로 수정하겠습니다. 빠른 확인 감사합니다 :)

현 리포에서도 PR을 진행해야 할까요? 아니면 공식 리포에서만 하면 될까요?

**Comment by 9bow** [comment]
이곳에서 수정해주신 내용이 tutorials.pytorch.kr 에 반영됩니다. :)
가능하시다면 공식 레포에도 기여해보시는 것도 좋을 것 같구요.

**Comment by 9bow** [comment]
오랜 기간 열려있어 제가 임의로 수정하였습니다. 이 이슈는 닫도록 하겠습니다. :)

**Comment by 9bow** [comment]
아래와 같이 @0xBono 님께서 발견하셨다는 내용을 포함하여 공식 레포에 [이슈](https://github.com/pytorch/tutorials/issues/1498)를 만들고 [PR](https://github.com/pytorch/tutorials/pull/1499)을 올렸습니다. ^^
> This typo is found by @0xBono on the Korean tutorial translation repo (9bow/PyTorch-tutorials-kr#198).
