### ISSUE TITLE
Learn The Basics을 번역해야 합니다

### ISSUE THREAD

**Issue by itsnamgyu** [9bow/PyTorch-tutorials-kr#209]
## 문서 URL
- **URL**: https://pytorch.org/tutorials/beginner/basics/intro.html

## 설명

파이토치 기본 튜토리얼이 60 minute blitz에서 새로운 시리즈로 바뀐 것 같습니다. 최근에 직접 진행해봤는데 내용 아주 좋았습니다.

번역 어떻게 진행할지 알려주시면 개별 이슈로 시간 나는대로 번역 작업 진행해보겠습니다!

<img width="1431" alt="KR" src="https://user-images.githubusercontent.com/23400562/114668398-a746d300-9d3b-11eb-8091-3581c8258196.png">

<img width="1429" alt="EN" src="https://user-images.githubusercontent.com/23400562/114668406-aa41c380-9d3b-11eb-99fa-0ce4e26a9923.png">

## (대략적인) 예상 완료 일정
- 모르겠습니다😭

## 관련 이슈
#90 (v1.6) ?

**Comment by 9bow** [comment]
이번 주말 중으로 1.8 버전의 튜토리얼을 반영해두도록 하겠습니다. +_+

**Comment by 9bow** [comment]
...1.6 이후 1.7을 건너뛰고 오래 묵혀두다보니 [예상보다 변경 사항이 많아서](https://github.com/pytorch/tutorials/compare/bc9cac0...4bd116438cf53dd4dad12abb972347e6fe2762ff) 시간이 조금 더 걸릴 것 같습니다. orz;;
1.8 버전의 튜토리얼이 반영되는대로 여기에 다시 덧글을 남기도록 하겠습니다. (_ _)

**Comment by 9bow** [comment]
안녕하세요, @itsnamgyu 님. 드디어 v1.8을 반영하였습니다!

하지만 이번에는 변경사항이 많은데다가 기본적인 튜토리얼 중에 날아간 것들이 있어서, 웹 사이트에 반영하기 전에 이것들을 먼저 번역하려고 합니다.
(대략 blitz에서는 2개 튜토리얼, 예제로 배우는 파이토치 튜토리얼에서는 모든 하위 튜토리얼들이 새로 변경되었는데요,
 이것들과 함께 본 이슈의 Learn the basics까지 반영된 후에 빌드를 새로 하려고 합니다.)

우선 제가 틈틈히 blitz와 예제로 배우는... 을 먼저 끝내고, 여유가 되면 요 이슈를 해결해보겠으니, 부담없이(!) 번역해주시길 부탁드립니다 ㅎㅎ

**Comment by 9bow** [comment]
@itsnamgyu 님, 진행 중인 번역 내용들을 #212 PR로 올려두었습니다.
(튜토리얼 순서대로) 계속 번역을 진행하며 하나의 튜토리얼이 완료될 때마다 추가 커밋을 하도록 하겠습니다.
혹시 진행하실 수 있는 상황이 되시면 부담없이 해당 브랜치(`trans_learn_the_basics`)에 PR 남겨주세요!

**Comment by itsnamgyu** [comment]
넵 감사합니다!
