### ISSUE TITLE
/beginner/nn_tutorial 오탈자 수정

### ISSUE THREAD

**Issue by Taeyoung96** [9bow/PyTorch-tutorials-kr#227]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- 수정이 필요한 URL : **https://tutorials.pytorch.kr/beginner/nn_tutorial.html**  

## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_  

`fit() 와 get_data() 생성하기` 에서 두 번째 문단 두 번째 문장에서 '전덜하지'를 '전달하지'로 바꾸어야 합니다.  

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._

**Comment by 9bow** [comment]
감사합니다. :)
혹시 PR도 만들어주실 수 있으실까요?

**Comment by Taeyoung96** [comment]
네! PR 만들도록 하겠습니다 😄
