### ISSUE TITLE
패러미터 -> 파라미터 수정

### ISSUE THREAD

**Issue by yuseungwoo** [9bow/PyTorch-tutorials-kr#299]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- **URL**:
/Users/airlab/Documents/PyTorch-tutorials-kr/beginner_source/chatbot_tutorial.py
## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_
패러미터 -> 파라미터 수정

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._

영어 발음을 한글로 표기시 이슈가 되는 부분이 많으나 "패러미터"와 같은 부분은 "파라미터"로 통용하고 있어 수정이 필요해 보입니다.

**Comment by hyoyoung** [comment]
현재 사용하고 있는 용어집에는 파라미터를 매개변수로 번역하고 있습니다.
매개변수로 바꾸는게 어떨까요?

**Comment by yuseungwoo** [comment]
수정 완료하였습니다.
