### ISSUE TITLE
원본 문서의 제목, 링크 추가 제안

### ISSUE THREAD

**Issue by spongebob03** [9bow/PyTorch-tutorials-kr#314]
## 이슈 내용
_어떤 이슈인지 알려주세요._
#### 파이토치 한국어 튜토리얼에서 그 페이지에 해당하는 원본 파이토치 튜토리얼의 링크나 제목 추가를 건의합니다. 
  - 예를 들어 [BUILD THE NEURAL NETWORK](https://pytorch.org/tutorials/beginner/basics/buildmodel_tutorial.html) 를 처음에 읽다가 번역의 필요성을 깨닫고 파이토치 한국어 사이트에서 [해당 번역](https://tutorials.pytorch.kr/beginner/basics/buildmodel_tutorial.html)을 찾을때 번역했을 제목을 생각해서 검색하거나 목차 위치를 비교해서 찾고 있는 경우가 많습니다. 
  -  주소창의 url을 보면 알 수있지만 사용자입장에서 이점을 인지하기 어려울것 같습니다
  - 공식문서에서 바로 해당 번역으로 갈 수 있다면 좋겠지만…일단 번역된 튜토리얼 문서에서 원본 문서의 링크나 제목을  읽을거리에 추가하는 정도면 영어 문서를 보다가 번역을 찾는 분들도 이전보다 빠르게 번역을 찾을 수 있을거 같습니다. 

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._

**Comment by 9bow** [comment]
@spongebob03 님, 좋은 제안 감사합니다. ^^
공식 문서에서 한국 문서로의 링크는 생각해보지 못했는데 다른 언어(중국어, 일어 등) 튜토리얼과 함께 링크를 추가할 수 있다면 좋을 것 같습니다.

(시간이 걸릴 것 같으니) 우선은 한국어 튜토리얼에서 공식 튜토리얼로의 링크를 추가하는 것을 먼저 진행해보면 어떨까 싶습니다.

혹시 링크 위치나 문구 등에 대해서도 의견 있으실까요?

또는, 아까 @Taeyoung96 님께서 말씀해주셨던 의견은 아래와 같이 사이트 하단의 **공식 문서(영어)** 부분에 링크를 걸되 보고 있던 페이지의 원본 문서가 있으면 해당 링크로 이동하는 것으로 이해했는데요, 이런 방식도 괜찮으실까요?
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/9343724/132126440-d3036d07-2e21-4e6a-b6ae-30a2edcae90e.png">

**Comment by spongebob03** [comment]
> 혹시 링크 위치나 문구 등에 대해서도 의견 있으실까요?

- 문구는 원본 제목으로도 해당 번역을 찾을 수 있도록 제목을 그대로 보여주는 링크를 생각하고있습니다.  위치는 다음 3가지 위치를 고려해봤습니다. 
  1. 상단 제목 윗부분의 링크들이 나열된 부분
![image](https://user-images.githubusercontent.com/34731006/132130457-01083bfc-9523-4483-b957-99d77f42c981.png)

  2. 상단 제목 아랫 부분
![image](https://user-images.githubusercontent.com/34731006/132130440-7d80991e-1c8c-4068-a425-05ba0a90ec44.png)

  2. 하단의 더 읽어보기 목록
![image](https://user-images.githubusercontent.com/34731006/132130575-b419c165-69b3-4b0d-b7c4-ab214d5a1e89.png)



> 또는, 아까 @Taeyoung96 님께서 말씀해주셨던 의견은 아래와 같이 사이트 하단의 **공식 문서(영어)** 부분에 링크를 걸되 보고 있던 페이지의 원본 문서가 있으면 해당 링크로 이동하는 것으로 이해했는데요, 이런 방식도 괜찮으실까요?

네. 이 방법은 생각하지 못했는데 좋은 방법이라고 생각했습니다! 다만 하단의 **공식 문서(영어)** 부분을 공식 문서 홈페이지(화면)으로 인식할 거 같습니다. 위치선정이나 방식은 다른 분들의 의견으로 결정하면 좋을거 같습니다.

**Comment by Taeyoung96** [comment]
선희님 의견을 들어봤을 때, 개인적으로는 '상단 제목 아랫 부분'이 괜찮아 보이긴 합니다.  
다만 걱정이 되는 것이 대다수의 번역 페이지를 수정을 해야해서... :cry:  
다른 분들의 의견을 받아보는 것도 좋은 것 같습니다!

**Comment by 9bow** [comment]
안녕하세요, @spongebob03 님, @Taeyoung96 님.

이미 추가된 문서 외에, 앞으로 추가되거나 번역될 튜토리얼 문서를 고려해봤을 때, 
가급적 튜토리얼 문서 페이지에 매번 뭔가 변경을 가하지 않는 것이 좋겠다는 생각을 해보았습니다.

관련하여 @spongebob03 님께서 의견주신 i), iii)의 `상단의 하위 문서 링크` 또는 `하단의 더 읽어보기` 경우에는
모든 문서에 일괄적으로 있는 부분이 아니라서 적용이 어려워보였습니다.

모든 문서에는 1번째 헤딩(heading1, `<h1>` 태그)는 모두 존재하기 때문에 제안주신 방법 중에서는 ii) 위주로 고민을 해봤는데요
역시 '원문 문서의 제목' 또한 사람의 손을 거치지 않고 자동으로 가져오게 하려니 애매한 부분이 있었습니다.

그래서 고민 끝에 (제안 주신 방법이랑 약간 거리는 있지만ㅠ) 아래와 같은 식으로 문서 제목 뒤에
`[원문 보기]`와 같은 버튼을 추가하고 눌렀을 때 새 창으로 원문 이동을 하게 만들어보았습니다.

대략 이런 방식이 될 것 같은데요, 혹시 이런 방식은 어떠실까요?
![image](https://user-images.githubusercontent.com/9343724/134795118-21f61179-cd4c-42aa-8407-8e0ec397caef.png)

추가로 @Taeyoung96 님이 제안주셨던 것처럼 하단의 `공식 문서로 이동` 부분의 링크도 원본 튜토리얼로 변경하는 것을 적용하려고 합니다.
![image](https://user-images.githubusercontent.com/9343724/134795147-64d90081-f4c4-458b-9e52-845b68702a34.png)

의견 부탁드립니다~

**Comment by Taeyoung96** [comment]
@9bow  
정환 멘토님께서 제안해주신 제목 옆에 `[원문 보기]` 버튼을 생성하는 것이 조금 더 가독성도 좋고 사람들이 많이 이용할 것 같다는 생각입니다!  
버튼 생성하는 것만 알려주시면 저희 컨트리뷰톤을 진행하는 분들과 배분을 해서 버튼을 생성하고 원본 링크로 옮기는 작업을 진행하면
정환 멘토님의 부담도 줄어들 것 같습니다! :smile:

**Comment by spongebob03** [comment]
@9bow 

>  i), iii)의 상단의 하위 문서 링크 또는 하단의 더 읽어보기 경우에는
모든 문서에 일괄적으로 있는 부분이 아니라서 적용이 어려워보였습니다.

이 점을 지금 알게되어서 ii번째 방안을 고려해서 만들어주신 예시처럼 `[원문 보기]`가 편할거 같습니다! (고민해주셔서 감사합니다) 
다만 저는 처음에 링크를 고려하게 된 이유 중 원문을 보다가 번역을 찾을 때 편의를 위한 부분도 있어서 혹시 `[원문 보기]`로 표시되어도 번역 사이트 검색에서 원문 제목으로 해당 번역을 찾을 수 있나요? 

> 이미 추가된 문서 외에, 앞으로 추가되거나 번역될 튜토리얼 문서를 고려해봤을 때,
가급적 튜토리얼 문서 페이지에 매번 뭔가 변경을 가하지 않는 방식이 좋겠다는 생각을 해보았습니다.

> 역시 '원문 문서의 제목' 또한 사람의 손을 거치지 않고 자동으로 가져오게 하려니 애매한 부분이 있었습니다.

`[원문 보기]`를 추가하는 방법은 자동으로 할 수 있나요? 추가 건의였기 때문에 최대한 멘토님과 컨트리뷰터들의 번역작업에 부담이 없는 방향이면 문제 없을거 같습니다. 여러 방법을 고려해주셔서 감사합니다!

**Comment by 9bow** [comment]
> 원문을 보다가 번역을 찾을 때 편의를 위한 부분도 있어서 혹시 [원문 보기]로 표시되어도 번역 사이트 검색에서 원문 제목으로 해당 번역을 찾을 수 있나요?
- 영어에서 한국어 사이트로의 이동 말씀이시죠? pytorch.org 에서 지원을 해줘야 할 것 같은데, 얘기도 해봐야 하고 시간도 걸릴 것 같습니다. ㅎㅎ
  (아직 번역이 덜 된 문서들이 있어서, 커버리지부터 높이고 얘기해볼 수 있을거 같구요 ^^; )

> [원문 보기]를 추가하는 방법은 자동으로 할 수 있나요..? 추가 건의였기 때문에 최대한 멘토님과 컨트리뷰터들의 번역작업에 부담이 없는 방향이 있다면 저도 더 찾아보겠습니다..!
- 네네, 현재는 Sphinx로 문서 빌드 시에 참조하는 [pytorch_sphinx_theme쪽](https://github.com/9bow/pytorch_sphinx_theme)을 고쳤구요, 조금 더 자세히는 javascript로 문서의 `<h1>` 태그를 찾아서 뒤에 `[원문 보기]` 링크를 붙이는 식으로 만들어두었습니다.
- 위와 같은 방식은 따로 문서 파일들(.rst / .py)은 변경 없이 일괄로 적용이 가능합니다. :)

추가로 `원문 보기`라는 문구는 괜찮으실까요? ^^;

괜찮으시다면 변경사항을 [pytorch_sphinx_theme쪽](https://github.com/9bow/pytorch_sphinx_theme) 저장소에 반영 후, 다시 빌드하도록 하겠습니다~

**Comment by spongebob03** [comment]
> 추가로 원문 보기라는 문구는 괜찮으실까요? ^^;

네. 제시해 주신 대로`원문 보기`로 표기하는 방안이 좋을 거 같습니다!
문구가 길지 않고 기능이 바로 명시되어 사용자도 바로 확인하기 쉬울거라 생각합니다😀

**Comment by Taeyoung96** [comment]
@9bow  
> 추가로 원문 보기라는 문구는 괜찮으실까요? ^^;  

저 또한 이 문구가 괜찮은 것 같습니다! :+1:

**Comment by 9bow** [comment]
9bow/pytorch_sphinx_theme@ddec9589e0d46a044780920649e741f8ef5964b1 에 변경 사항을 반영하였습니다. :)

**Comment by 9bow** [comment]
새로 빌드하여 적용하였습니다. 
제가 확인하기는 하였는데요, 혹시나 이상한 부분 발견하시면 알려주시기를 부탁드립니다. 감사합니다!
![image](https://user-images.githubusercontent.com/9343724/134949640-a6adff0c-850e-4f6a-8efe-12bc379e50da.png)

**Comment by spongebob03** [comment]
저도 확인했을 때 `[원문 보기]`, 하단의 `공식 문서로 이동`모두 문제 없이 원본으로 잘 이동합니다👍

**Comment by 9bow** [comment]
감사합니다. 이 이슈는 이제 닫도록 하겠습니다. 👍
