### ISSUE TITLE
"PyTorch로 분산 어플리케이션 개발하기" 내용 수정

### ISSUE THREAD

**Issue by hankyul2** [9bow/PyTorch-tutorials-kr#321]
안녕하세요. 좋은 번역 항상 감사합니다. 

## 문서 URL
- **https://tutorials.pytorch.kr/intermediate/dist_tuto.html**:

## 변경 사항
(1) 변경 전
- `dist.broadcast(tensor, src, group)` : `src` 의 `tensor` 를 모든 프로세스에 복사합니다.
- `dist.reduce(tensor, dst, op, group)` : `op` 를 모든 `tensor` 에 적용한 뒤 결과를 `dst` 에 저장합니다.
- `dist.all_reduce(tensor, op, group)` : 리듀스와 동일하지만, 결과가 모든 프로세스에 저장됩니다.
- `dist.scatter(tensor, scatter_list, src, group)` : i 번째 Tensor `scatter_list[i]` 를 i번째 프로세스에 복사합니다.
- `dist.gather(tensor, gather_list, dst, group)` : `dst` 의 모든 프로세스에서 `tensor` 를 복사합니다.
- `dist.all_gather(tensor_list, tensor, group)` : 모든 프로세스의 `tensor` 를 모든 프로세스의 `tensor_list` 에 복사합니다.
- `dist.barrier(group)` : *group* 내의 모든 프로세스가 이 함수에 진입할 때까지 *group* 내의 모든 프로세스를 멈춥(block)니다.

(2) 변경 후
- `dist.broadcast(tensor, src, group)` : `src` 의 `tensor` 를 모든 프로세스**의 `tensor`에** 복사합니다.
- `dist.reduce(tensor, dst, op, group)` : `op` 를 모든 `tensor` 에 적용한 뒤 결과를 `dst` **프로세스의 `tensor`에** 저장합니다.
- `dist.all_reduce(tensor, op, group)` : 리듀스와 동일하지만, 결과가 모든 프로세스**의 `tensor`에** 저장됩니다.
- `dist.scatter(tensor, scatter_list, src, group)` : i 번째 Tensor `scatter_list[i]` 를 i번째 프로세스의 **`tensor`에** 복사합니다.
- `dist.gather(tensor, gather_list, dst, group)` : **모든 프로세스의 `tensor` 를 `dst` 프로세스의 `gather_list`에 복사합니다.**
- `dist.all_gather(tensor_list, tensor, group)` : 모든 프로세스의 `tensor` 를 모든 프로세스의 `tensor_list` 에 복사합니다.
- `dist.barrier(group)` : *group* 내의 모든 프로세스가 이 함수에 진입할 때까지 *group* 내의 모든 프로세스를 멈춥(block)니다.

## 추가 정보
목적어를 추가했습니다.

감사합니다.

**Comment by 9bow** [comment]
안녕하세요, @hankyul2 님.
개선 사항에 대한 좋은 제안 감사합니다. 더 명료해진 것 같습니다. 👍 
혹시 PR(Pull Request)도 만들어주실 수 있으실까요?
