### ISSUE TITLE
beginner/deeplabv3_on_ios 번역 예정입니다.

### ISSUE THREAD

**Issue by sojeongii** [9bow/PyTorch-tutorials-kr#367]
## 문서 URL
_번역을 하실 / 요청하실 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/saving_loading_models.html)_
- **URL**: https://tutorials.pytorch.kr/beginner/deeplabv3_on_ios.html

## (대략적인) 예상 완료 일정
_예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)_<br />
_(반드시 지키셔야 하는 일정이 아닙니다 - 일정이 너무 늦어질 경우 다른 번역자를 위해 남겨주세요.)_
* 예상 완료 일정: 11월 15일

## 관련 이슈
_현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다._ <br />
_(특별한 일이 없다면 변경하지 않으셔도 됩니다.)_
* 관련 이슈: #221 (v1.9)

**Comment by des00** [comment]
혹시 번역 시작하셨나요?
#343 으로 진행을 하고 있어 차주중에 PR 올리고자 합니다.

**Comment by sojeongii** [comment]
저는 아직 시작 안했습니다.
날짜: 2021.11.07 오후 08:21:09 (GMT+09:00)
제목: Re: [9bow/PyTorch-tutorials-kr] beginner/deeplabv3_on_ios 번역 예정입니다. (Issue #367)

혹시 번역 시작하셨나요?
#343 으로 진행을 하고 있어 차주중에 PR 올리고자 합니다.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by des00** [comment]
> 저는 아직 시작 안했습니다. 날짜: 2021.11.07 오후 08:21:09 (GMT+09:00) 제목: Re: [9bow/PyTorch-tutorials-kr] beginner/deeplabv3_on_ios 번역 예정입니다. (Issue #367) 혹시 번역 시작하셨나요? #343 으로 진행을 하고 있어 차주중에 PR 올리고자 합니다. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

아직 시작 안하셨으면 본 이슈는 closed하시고 이슈로등록되지 않은 문서 번역하시는게 좋을듯 싶습니다.

**Comment by sojeongii** [comment]
저는 아직 시작 안했습니다. 날짜: 2021.11.07 오후 08:21:09 (GMT+09:00) 제목: Re: [9bow/PyTorch-tutorials-kr] beginner/deeplabv3_on_ios 번역 예정입니다. (Issue #367) 혹시 번역 시작하셨나요? #343 으로 진행을 하고 있어 차주중에 PR 올리고자 합니다. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

아직 시작 안하셨으면 본 이슈는 closed하시고 이슈로등록되지 않은 문서 번역하시는게 좋을듯 싶습니다.
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 9bow** [comment]
최근에 갑자기 GitHub을 많이 사용하지 않으셨던 분들께서 이슈를 올려주고 계시는데요,
혹시 다른 이슈들 올리신 분들과 같은 조직에 계시는지요?

대부분의 오픈소스 프로젝트에는 [CONTIRUTING.md](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)과 같이 기여하는 방법에 대해서 정리해둔 문서가 있으니 먼저 읽어주시기를 부탁드리며,
혹시나 학교나 다른 곳에서 함께 어떤 과정의 일환으로 이 저장소에 기여를 진행하고 계시다면 알려주시기를 부탁드립니다.

감사합니다.

**Comment by sojeongii** [comment]
학교 전공 팀프로젝트의 일환으로 오픈소스 기여 과제가 있습니다.
문서화를 진행하는 다른 팀이 몇몇 이슈를 올린 것 같습니다.
오픈소스 기여를 처음해봐서 많이 미흡했습니다.
CONTRIBUTING.md를 좀 더 꼼꼼히 읽어보겠습니다.
이슈를 요청한 뒤에 해당 내용에 기여가 필요한지 여부는 언제 알 수 있을까요?
과제 마감기간이 있어서 다른 문서를 찾아봐야 하는지 알고 싶습니다.
 
-----Original Message-----

**Comment by 9bow** [comment]
네, 이슈를 남겨주시기를 요청드리는 이유가 다른 기여자가 이미 문서를 번역 중에 있는 상황일 수 있기 때문입니다.
기존에 올라온 이슈들을 검색해보시고 이미 번역이 진행 중이 아니라는 판단이 되신다면 번역하여 기여해주시면 됩니다.

기본적으로 번역 PR을 리뷰하는데 걸리는 시간은 번역에 걸리는 시간에 준하거나 그 이상인 경우들이 많습니다. 
(경험적으로 PyTorch에 익숙하지 않으시거나 번역을 처음 접하시는 분들의 결과물들이 특히 그렇습니다.)
또한 본 저장소의 PR에 대한 리뷰는 소수의 인원에 의해 이뤄지다보니 반영이 느린 편임을 양지해주시기 바랍니다.

최근에 올라온 다수의 이슈들이 기존에 PyTorch를 사용하시거나 학습하지 않으시던 분들께서 (오픈소스 기여 그 자체가 아닌) 학점을 목적으로 기한을 정하여 진행하시는 기여 활동이시라면, 저장소 관리자들의 노력을 허비하지 않도록 유의하여 주시기를 미리 부탁드립니다. 특히 문서에 대한 기여는 동작 여부가 CI/CD 등으로 명확히 확인이 가능한 코드에 대한 기여와는 다른 종류이기 때문에 번역의 품질 뿐만 아니라 기존의 다른 문서들과의 용어 / 스타일 등에 대한 일관성 또한 중요함을 명확히 이해해주시기를 부탁드립니다.

개인적으로는 이미 URL만 복붙하셔서 남기시는 이슈들의 형태 및 번역하시려는 문서들의 주제가 매우 다른 경우들이 많아 심히 우려가 되는데요, 모쪼록 이 내용을 이번 과제를 함께 진행하시는 동료분들 및 교강사분께도 전해주시기를 부탁드립니다.

감사합니다.
감사합니다.

**Comment by sojeongii** [comment]
알려주신 부분을 고려해서 3명이 한 이슈에 대하여 같이 진행해도 될까요?
같이 한다면 이슈를 다시 신청해야 하는지 문의 드립니다.
다른 팀에 대한 정보는 이름밖에 정보를 알지 못하여 미리 이 내용을 전하지 못할 것 같습니다.
중간발표 점검 때 이러한 부분을 언급하여 다른 팀들도 알 수 있도록 발표하겠습니다.
 
-----Original Message-----

**Comment by 9bow** [comment]
번역의 주체가 반드시 한 분일 필요는 없습니다. 하지만 본 저장소 기준으로 하나의 PR은 하나(이상)의 문서에 대해서 완결적으로 번역된 내용을 포함해야 합니다.
개인적으로는 하나의 문서를 2명 이상이 공동 번역을 하는 경우의 품질 또한 경험적으로 좋았던 적이 별로 없기에 권하고 싶은 방법은 아닙니다.

가능하시다면 교강사분의 연락처(이메일)를 알려주시거나, 본 이슈에 덧글 또는 저장소에 새로운 이슈를 남겨주시도록 전달해주실 수 있으실까요?

**Comment by sojeongii** [comment]
그러면 저희 팀은 다른 방안을 찾아보겠습니다.
과제는 오픈소스 기여 방안 중 하나를 선택해서 진행하기 때문에 학생들이 우연히 겹치게 된 것 같습니다.
내일 같은 수업을 듣는 학생들에게 걱정하신 부분들을 잘 이야기 해보겠습니다.
 
-----Original Message-----
