### ISSUE TITLE
Point-to-point communication을 점대점 통신으로 번역

### ISSUE THREAD

**Issue by jessemin** [9bow/PyTorch-tutorials-kr#37]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/pytorch_with_examples.html)_
- **URL**: https://tutorials.pytorch.kr/intermediate/dist_tuto.html

## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_
Point-to-point communication을 "지점대지점 간 통신" 대신 "점대점 통신"으로 번역하는 것을 제안합니다.

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._
http://ap2.khu.ac.kr/download/mpi_lec.pdf 또는 http://www.ktword.co.kr/word/abbr_view.php?m_temp1=3264 등의 자료 등을 참조한 결과 "점대점 통신"이 조금 더 자연스러운 것 같아 제안합니다 :)

**Comment by 9bow** [comment]
네, 해당 튜토리얼을 번역하며 `지점 대 지점 간 통신`과 `점 대 점 통신` 사이에서 고민이 좀 있었는데요,
[TTA 용어 사전](http://word.tta.or.kr/)에서도 단어에 따라 혼용하고 있어 ([지점 대 지점 간 통신](http://word.tta.or.kr/mobile/dictionaryView.do?word_seq=052378-1) 및 [점 대 점 연결 방식](http://word.tta.or.kr/mobile/dictionaryView.do?word_seq=052380-2)) `점` 보다는 `지점`이라는 단어가 이해하는데 있어서 수월할 것 같다는 개인적 판단(...)으로 지점이라는 단어를 사용했었습니다.
링크해주신 것처럼 확실히 `지점 대 지점`보다는 `점 대 점`으로 번역이 더 자주되는 것 같은데요, 아래 단어들까지 포함하여 조금 더 의견을 교환 / 고민해보고 결정하는건 어떠실까요?

* 점 대 점 통신
* 지점 간 통신
* 일대일 통신

**Comment by jessemin** [comment]
네 좋은 생각인거 같습니다~

**Comment by 9bow** [comment]
@bongmo 님, @adonisues 님, 의견 부탁드립니다~

**Comment by 9bow** [comment]
오랜기간 별다른 토의가 없어 `지점-대-지점`을 `점-대-점`으로 개선하고 본 이슈를 닫습니다.

@jessemin 님, 잘 지내시죠? :)
