### ISSUE TITLE
'torchtext와 함께하는 언어 번역(LANGUAGE TRANSLATION WITH TORCHTEXT)'을 번역합니다.

### ISSUE THREAD

**Issue by ardeness** [9bow/PyTorch-tutorials-kr#48]
## 문서 URL
- **URL**: https://pytorch.org/tutorials/beginner/torchtext_translation_tutorial.html

## (대략적인) 예상 완료 일정
- 3월 말까지 가능합니다.
## 관련 이슈
_현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다._ <br />
_(특별한 일이 없다면 수정하지 않으셔도 됩니다.)_
#14 (v1.3)

**Comment by 9bow** [comment]
감사합니다! '언어 번역'은 어떨까요?

**Comment by 9bow** [comment]
#51 로 반영되었습니다. :)
