### ISSUE TITLE
단어 임베딩 튜토리얼 번역

### ISSUE THREAD

**Issue by sylim2357** [9bow/PyTorch-tutorials-kr#57]
## 문서 URL
번역을 하실 / 요청하실 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/saving_loading_models.html)

- URL: https://tutorials.pytorch.kr/beginner/nlp/word_embeddings_tutorial.html

## (대략적인) 예상 완료 일정
예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)

(반드시 지키셔야 하는 일정이 아닙니다 - 일정이 너무 늦어질 경우 다른 번역자를 위해 남겨주세요.)
4월 중

## 관련 이슈
현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다.

(특별한 일이 없다면 수정하지 않으셔도 됩니다.)
#53 (v1.4)

**Comment by sylim2357** [comment]
번역 하는 중입니다.

**Comment by 9bow** [comment]
네, 완료되시면 PR 부탁드립니다. 감사합니다! :)

**Comment by sylim2357** [comment]
merge 감사합니다.
