### ISSUE TITLE
SEQUENCE-TO-SEQUENCE MODELING WITH NN.TRANSFORMER AND TORCHTEXT 번역

### ISSUE THREAD

**Issue by namdori61** [9bow/PyTorch-tutorials-kr#59]
## 문서 URL
_번역을 하실 / 요청하실 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/saving_loading_models.html)_
- **URL**: https://tutorials.pytorch.kr/beginner/transformer_tutorial.html

## (대략적인) 예상 완료 일정
_예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)_<br />
_(반드시 지키셔야 하는 일정이 아닙니다 - 일정이 너무 늦어질 경우 다른 번역자를 위해 남겨주세요.)_

4월 중 완료 예상

## 관련 이슈
_현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다._ <br />
_(특별한 일이 없다면 수정하지 않으셔도 됩니다.)_
#53 (v1.4)

**Comment by namdori61** [comment]
감사합니다! 번역중입니다.

**Comment by 9bow** [comment]
감사합니다. 완료되시면 PR 부탁드립니다. 👍

**Comment by 9bow** [comment]
빌드가 완료되어 튜토리얼 사이트에 반영되었으니 확인 부탁드립니다. :) 
https://tutorials.pytorch.kr/beginner/beginner/transformer_tutorial.html

**Comment by namdori61** [comment]
안녕하세요! 반영 감사합니다 :)
위에 주신 링크는 beginner/ 가 반복되서 404 에러 뜨네요ㅠ
사이트에서는 아래와 같이 정상적으로 사이트에 반영된 것 확인했습니다! 감사합니다.
https://tutorials.pytorch.kr/beginner/transformer_tutorial.html

**Comment by 9bow** [comment]
앗, 그러게요. ^^;;
확인하고 URL을 붙여넣는 도중에 클립보드가 날아가 이거저거하다가 잘못 복붙한 것 같습니다 T_T
번거롭게 해드려 죄송합니다. ^^;
