### ISSUE TITLE
WHAT IS TORCH.NN REALLY? 번역

### ISSUE THREAD

**Issue by namdori61** [9bow/PyTorch-tutorials-kr#66]
## 문서 URL
_번역을 하실 / 요청하실 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/saving_loading_models.html)_
- **URL**: https://tutorials.pytorch.kr/beginner/nn_tutorial.html

## (대략적인) 예상 완료 일정
_예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)_<br />
_(반드시 지키셔야 하는 일정이 아닙니다 - 일정이 너무 늦어질 경우 다른 번역자를 위해 남겨주세요.)_
6월 중순 -> 7월 4째주 (지연)

## 관련 이슈
_현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다._ <br />
_(특별한 일이 없다면 수정하지 않으셔도 됩니다.)_
#53 (v1.4)

**Comment by namdori61** [comment]
@9bow 안녕하세요! 번역 진행해도 될까요??

**Comment by 9bow** [comment]
앗, 넵. 물론입니다. (기다리고 있었습니다. ^^)
이슈를 올려주십사 요청드리는 것은 같은 문서를 서로 다른 분들께서 진행하시는 것 때문이고, 별도로 제가 승인을 해드리거나 하는 것은 전혀 아니었는데, 혼란을 드려 죄송합니다. (_ _)

**Comment by 9bow** [comment]
다만 조만간 있을 1.5 튜토리얼 반영 시에 원문이 달라질 수 있으니, 이 부분만 참고 부탁드립니다!

**Comment by namdori61** [comment]
아 제가 착각했네요ㅠ 별도로 코멘트 해주시면 진행하는줄 알고 있었습니다. 죄송합니다 :)

**Comment by 9bow** [comment]
[기여하기](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md) 문서를 다시 확인해보니 제가 오해가 있도록 적은 것 같습니다. ^^;
의도했던 것은 '(오타 수정 등에 있어서) 의도된 바일 수 있으니 (PR 전에) 먼저 이슈로 협의하는 것이 필요하다'는 것이었는데, 설명이 충분치 못한 것 같습니다. 오타 수정을 포함하여 기여하기 문서를 수정하도록 하겠습니다.
감사합니다!

**Comment by namdori61** [comment]
피드백 및 수정 감사드립니다 :)

**Comment by namdori61** [comment]
안녕하세요, 번역 완료 일정보다 많이 늦어진 점 죄송합니다. 일단 7월 내에 완료하는 것으로 일정을 변경했는데, 다른 분께서 진행하시지 않는다면 제가 계속 진행하겠습니다.

**Comment by 9bow** [comment]
네, 다른 분께서 따로 요청이 없으셨으니 진행해주시면 될 것 같습니다. 감사합니다! :)

**Comment by creduo** [comment]
@namdori61 안녕하세요, 다른 분께서 번역을 희망하시는 분이 있어서 진행경과를 여쭙고자 합니다. 혹시 현재 번역을 진행중이실까요?

**Comment by namdori61** [comment]
안녕하세요! 현재 번역 진행중입니다. 금주 주말까지 완료하려고 합니다. 번역이 예정된 일정보다 늦어져 정말 죄송합니다.

**Comment by namdori61** [comment]
안녕하세요, py파일에 번역을 완료하였으나 제 컴퓨터에서 빌드를 해보니 예전 (영어) 파일로 변환되어 버립니다.
해당 경우에는 rst 파일에 번역을 적용하면 될까요?

**Comment by 9bow** [comment]
안녕하세요, [원본 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/beginner_source/nn_tutorial.py)가 `.py` 파일인데 `.rst` 파일을 보셨다는걸 보니, 아마도 `beginner_source/` 디렉토리가 아닌, 빌드 결과물로 생기는 `beginner` 디렉토리의 파일을 번역하신 것 같습니다.
`*_source/` 디렉토리에 있는 파일들이 원본 파일이므로, 해당 파일들을 기준으로 번역 후 다시 빌드 해봐주시기를 요청드립니다.
감사합니다. ^^

**Comment by namdori61** [comment]
답변 감사합니다! 제가 착가했네요, 말씀해주신데로 beginner_source 디렉토리에서 수정하니 정상 빌드 됩니다:)

**Comment by namdori61** [comment]
안녕하세요, 질문이 많아 죄송합니다ㅠ
Pull Request 하기 이전에 2가지 질문이 있습니다.

1. 홈페이지 버젼이 1.6.0으로 업데이트 되었는데, 제가 현재 fork한 버젼은 이전 버젼인 1.5.0입니다. 혹시 PR 이전에 어떻게 프로세스를 진행하면 될까요? (오픈소스 프로젝트가 처음이라 미숙한 점 양해 부탁드립니다!)

2. 제 컴퓨터에서 코드 빌드했을 경우에, 기존에는 코드 블락 안에서 실행되어 결과가 웹페이지에 제공 되었던 (예를 들면, print문의 결과 값) 것이 실행이 안되는데 혹시 관련해서 이슈가 있을까요?

바쁘실텐데 답변해주셔서 정말 감사드립니다 :)

**Comment by 9bow** [comment]
네, 다행이네요. :)

1-1. PR을 만드실 때, 어떤 변경 사항 / Commit들을 PR로 만드는 것인지 보실 수 있습니다. 진행하시는 튜토리얼은 1.5 -> 1.6 사이에 변경 사항이 없었던 것으로 기억하고 있습니다. (정확히지는 않습니다; )
1-2. 걱정이 되신다면 (& 다른 프로젝트들에 PR을 고려 중이시라면) 이미 fork 하셨던 @namdori61 님의 저장소를 최신으로 업데이트하시는 것도 방법입니다. [설명된 블로그 글](https://jybaek.tistory.com/775)을 링크하오니 참고 부탁드립니다.
2. 혹시 빌드하실 때 사용하신 명령어가 달라지지는 않았는지요? `make docs`는 튜토리얼 내부의 코드 블럭들을 모두 실행하는 식으로 빌드하지만, `make html-noplot`은 코드 블럭은 실행하지 않고, html 파일만 생성하고 있습니다. 이전에는 전자로, 최근에는 후자로 빌드하신 것은 아니실까요?

항상 감사합니다~

**Comment by namdori61** [comment]
바쁘실텐데 항상 자세하게 답변해주셔서 정말 감사합니다!

답변주신대로, 1-2로 업데이트 후 PR하고 2에서 `make docs`로 제 컴퓨터에서 빌드 실행해서 확인해보겠습니다.

감사합니다:)

**Comment by 9bow** [comment]
안녕하세요, @namdori61 님.
번역해주신 내용이 https://tutorials.pytorch.kr/beginner/nn_tutorial.html 와 같이 반영되었으니 확인 부탁드립니다~ ^^
감사합니다 👍
