### ISSUE TITLE
intermediate_source/pruning_tutorial 번역

### ISSUE THREAD

**Issue by mindongjun** [9bow/PyTorch-tutorials-kr#79]
## 문서 URL
_번역을 하실 / 요청하실 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/saving_loading_models.html)_

- **URL**: https://tutorials.pytorch.kr/intermediate/pruning_tutorial.html?highlight=compression#

## (대략적인) 예상 완료 일정
_예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)_<br />
_(반드시 지키셔야 하는 일정이 아닙니다 - 일정이 너무 늦어질 경우 다른 번역자를 위해 남겨주세요.)_

8월 중순-말까지 번역할 수 있을 것 같습니다.

## 관련 이슈
_현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다._ <br />
_(특별한 일이 없다면 수정하지 않으셔도 됩니다.)_
#68 (v1.5)

**Comment by 9bow** [comment]
번역 완료되시면 Pull Request 부탁드립니다. :)

**Comment by 9bow** [comment]
오랜기간 진행이 없어 (& 다른 분께서 이미 번역을 완료하셔서) 본 이슈를 닫습니다. 
해당 튜토리얼에 추가적인 기여를 진행하실 때에는 새로운 이슈를 다시 열어주시기를 부탁드립니다.
