### ISSUE TITLE
용어집 개선 사항

### ISSUE THREAD

**Issue by itsnamgyu** [9bow/PyTorch-tutorials-kr#85]
## 이슈 내용
좀 전에 올라온 용어집에서 몇가지 단어에 관해 피드백 사항이 있습니다!

### Production Use

- 운영환경에서 사용 > 상용 환경에서 사용

### in-place

- 바꿔치기 > in-place / 제자리
  한글로 번역하면 혼란이 발생할 것 같습니다. 한글로 한다면 제자리가 좀더 본 의미에 가깝지 않을까 생각합니다.

### shape

- 모양 > shape
  기존 사용자분들께서 파악하기 쉽고, 초보자 분들도 검색이 필요하더라도 "shape" 개념에 익숙해지시면 좋을것 같습니다 (기초 개념)

### mean-squared error

- 최소제곱오차 > 평균제곱오차
  오타

### Normalization

- 일반화 > 정규화
  위 normalizing에서는 정규화로 번역되어 있습니다

### Batch Nomarlization > Normalization

- 오타

**Comment by 9bow** [comment]
모두 다 변경이 필요한 내용 같습니다. 감사합니다!
특히 MSE는 실제 문서에서도 저렇게 되어 있나 확인이 필요할 것 같네요;; 알려주셔서 감사합니다!

**Comment by 9bow** [comment]
@itsnamgyu 
위 내용 PR로 만들어주실 수 있으실까요?

**Comment by itsnamgyu** [comment]
넵 곧 올리겠습니다!

**Comment by itsnamgyu** [comment]
> 모두 다 변경이 필요한 내용 같습니다. 감사합니다!
> 특히 MSE는 실제 문서에서도 저렇게 되어 있나 확인이 필요할 것 같네요;; 알려주셔서 감사합니다!

레포 검색 결과 평균제곱오차만 있고 `r'최소 *제곱 *오차'`는 없습니다!
