### ISSUE TITLE
recipes/defining_a_neural_network.py 번역

### ISSUE THREAD

**Issue by potatochips178** [9bow/PyTorch-tutorials-kr#88]
## 문서 URL
_번역을 하실 / 요청하실 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/saving_loading_models.html)_
- **URL**: https://tutorials.pytorch.kr/recipes/recipes/defining_a_neural_network.html

## (대략적인) 예상 완료 일정
_예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)_<br />
8월 8일 토요일

## 관련 이슈
_현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다._ <br />
_(특별한 일이 없다면 수정하지 않으셔도 됩니다.)_
#90 (v1.6)

**Comment by 9bow** [comment]
감사합니다! 레시피의 경우에는 [레시피 목록](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/recipes_source/recipes_index.rst)의 설명도 함께 번역이 돼야 합니다.
번역하시려는 레시피에 해당하는 설명도 함께 반영 부탁드립니다. :)

**Comment by JaeLee18** [comment]
컨트리뷰톤-리뷰 진행하였습니다.

**Comment by 9bow** [comment]
안녕하세요 @potatochips178 님, @JaeLee18  님
번역해주시고 리뷰해주신 빌드 결과물이 https://tutorials.pytorch.kr/recipes/recipes/defining_a_neural_network.html 와 같이 반영되었으니 확인 부탁드립니다. 
감사합니다! 👍
