### ISSUE TITLE
recipes/tensorboard_with_pytorch.py 번역

### ISSUE THREAD

**Issue by hy21116** [9bow/PyTorch-tutorials-kr#91]
## 문서 URL
_번역을 하실 / 요청하실 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/saving_loading_models.html)_
- **URL**: https://tutorials.pytorch.kr/recipes/recipes/tensorboard_with_pytorch.html

## (대략적인) 예상 완료 일정
_예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)_<br />
_(반드시 지키셔야 하는 일정이 아닙니다 - 일정이 너무 늦어질 경우 다른 번역자를 위해 남겨주세요.)_
8월 8일

## 관련 이슈
_현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다._ <br />
_(특별한 일이 없다면 수정하지 않으셔도 됩니다.)_
#90 (v1.6)

**Comment by 9bow** [comment]
감사합니다! 레시피의 경우에는 [레시피 목록](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/recipes_source/recipes_index.rst)의 설명도 함께 번역이 돼야 합니다. 번역하시려는 레시피에 해당하는 설명도 함께 번역하여 PR 부탁드립니다. :)
(더불어 여유가 있으시면 유사한 [TensorBoard 튜토리얼](https://tutorials.pytorch.kr/intermediate/tensorboard_tutorial.html)에 오역이나 이해하기 어려운 부분이 있으신지도 함께 살펴봐주시기를 부탁드립니다. ^^;)

**Comment by Justin-A** [comment]
컨트리뷰톤 - 리뷰 진행합니다.
